language: python

python:
  - 3.6
  # - 3.7

install:
  - pip install poetry
  - poetry install
  - poetry develop

script:
  - pytest

notifications:
  email:
    on_success: never
    on_failure: change
