language: python
dist: xenial

python:
  - 3.6
  - 3.7

install:
  - pip install poetry
  - poetry install
  - poetry develop

script:
  - poetry run flake8 .
  - poetry run pytest
  - poetry run mypy final_class.py
  - poetry check
  - poetry run pip check
  - poetry run safety check --bare --full-report

notifications:
  email:
    on_success: never
    on_failure: change
